In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('./train.csv')
train_data.head()
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1,2,3,4], dtype = np.float)

array([1., 2., 3., 4.])

In [5]:
np.array([range(i,i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((2,3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [9]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.linspace(1,100,5, dtype = int)

array([  1,  25,  50,  75, 100])

In [11]:
##난수 생성 관련
np.random.random((3,3))

array([[0.68692768, 0.38347626, 0.24905471],
       [0.69785807, 0.50511483, 0.66696618],
       [0.71226213, 0.06978818, 0.99323296]])

In [12]:
np.random.randint(0,10,(3,3))

array([[1, 6, 9],
       [6, 2, 3],
       [9, 8, 8]])

In [13]:
np.random.normal(0,1,(3,3)) ## 평균 = 0, 표준편차 =1

array([[-0.16695622,  1.59228889, -1.00119778],
       [ 1.11128741,  0.33524954,  0.53757962],
       [ 0.0872516 , -1.94037361,  0.2093069 ]])

In [14]:
np.random.seed(0) ## 0은 임의의 수, seed 함수를 사용하면 이 셀 안에서는 동일한 결과 출력가능(재현성)
arr1 = np.random.randint(10 , size=6) ## 0부터 10까지의 숫자 6개
arr2 = np.random.randint(10, size = (2,3))

print("arr1:\n%s"%arr1)
print("ndim : %d, shape : %s, size = %d, dtype : %s\n" % (arr1.ndim, arr1.shape, arr1.size, arr1.dtype))




arr1:
[5 0 3 3 7 9]
ndim : 1, shape : (6,), size = 6, dtype : int32



In [15]:
arr1

array([5, 0, 3, 3, 7, 9])

In [16]:
arr1[0]

5

In [17]:
arr1[-5]

0

In [18]:
arr2

array([[3, 5, 2],
       [4, 7, 6]])

In [19]:
arr2[0,0], arr2[1,2]

(3, 6)

In [20]:
arr2[0,0] = 66
arr2

array([[66,  5,  2],
       [ 4,  7,  6]])

In [21]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr1[0:5:1] ## start end step

array([0, 1, 2, 3, 4])

In [23]:
print(arr1[:5:]) ## [0:5:1]
print(arr1[:5])

[0 1 2 3 4]
[0 1 2 3 4]


In [24]:
arr1[2:8:2]

array([2, 4, 6])

In [25]:
arr2 = np.arange(12).reshape(-1,4) ## 행이 -1인 이유는 정해지지 않았다
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr2[:3, :4] ## 0 3 1, 0 4 1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
arr2[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

In [28]:
arr2[:2, 2::-1]

array([[2, 1, 0],
       [6, 5, 4]])

In [29]:
arr2[1:, -1]

array([ 7, 11])

In [30]:
list1 = [1,2,3]
list2 = [4,5,6]

In [31]:
np.concatenate([list1, list2])

array([1, 2, 3, 4, 5, 6])

In [32]:
arr1 = np.concatenate([list1, list2], axis = 0)
arr1

array([1, 2, 3, 4, 5, 6])

In [33]:
arr2 = arr1.reshape(-1,3)
arr2
np.sort(arr2, axis = 1)



array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([arr2, arr2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [35]:
aaa = np.vstack([arr2, arr2])
print(aaa)

print()
bbb = np.sort(aaa[1:],axis = 1)
print(bbb)


[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[4 5 6]
 [1 2 3]
 [4 5 6]]


In [36]:
np.hstack([arr2, arr2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [37]:
np.random.seed(0)

arr2 = np.random.randint(1,10,(3,4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [38]:
np.sum(arr2), arr2.sum()

(65, 65)

In [39]:
np.sum(arr2, axis = 1)

array([15, 21, 29])

In [40]:
np.sum(arr2, axis = 0)

array([19, 13, 17, 16])

In [41]:
np.min(arr2, axis = 1)

array([1, 3, 5])

In [42]:
np.random.seed(0)
X = np.random.random((10,3))
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [43]:
Xmean = X.mean(axis = 0)
Xmean

array([0.52101579, 0.62614181, 0.59620338])

In [44]:
Xcentered = X - Xmean
Xcentered

array([[ 0.02779771,  0.08904756,  0.00655999],
       [ 0.02386739, -0.20248701,  0.04969073],
       [-0.08342858,  0.26563119,  0.36745938],
       [-0.13757427,  0.16558323, -0.06730846],
       [ 0.04702877,  0.29945483, -0.52516732],
       [-0.43388649, -0.60592341,  0.23641646],
       [ 0.25714096,  0.24387034,  0.38241496],
       [ 0.27814277, -0.16466245,  0.18432579],
       [-0.40274137,  0.01377921, -0.45285009],
       [ 0.42365312, -0.10429349, -0.18154144]])

In [45]:
## 부울배열과 마스킹연산
np.random.seed(0)

X = np.random.randint(1,10, size = (3,4))
X

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [46]:
(X > 5) & (X < 8)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [47]:
np.sum((X > 5) & (X < 8))

3

In [48]:
np.sum((X > 5) | (X < 8))

12

In [49]:
X[(X > 5) & (X < 8)] ## 실제값을 얻을때

array([6, 6, 7])

In [50]:
## 팬시인덱싱 : 인덱스를 담고 있는 배열
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
row = np.array([0,1,2])
col = np.array([1,2,3])

In [52]:
X[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
X[:,col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [54]:
X[row,col]

array([ 1,  6, 11])

In [55]:
X[row.reshape(-1,1), col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [56]:
X = np.zeros(12).reshape(3,4)
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
X[1,0] =1
X

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
X[1,[1,3]] = 1 ## [1,3] 부분은 팬시 인덱싱
X

array([[0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [59]:
X[[0,2,1], [1,3,2]] =2
X

array([[0., 2., 0., 0.],
       [1., 1., 2., 1.],
       [0., 0., 0., 2.]])

In [60]:
X[0:3, [0,2]] =3
X

array([[3., 2., 3., 0.],
       [3., 1., 3., 1.],
       [3., 0., 3., 2.]])

In [61]:
np.random.seed(0)

x = np.array(np.random.randint(10, size=5))
x

array([5, 0, 3, 3, 7])

In [62]:
np.sort(x) ## x의 원본은 변하지 않음

array([0, 3, 3, 5, 7])

In [63]:
x

array([5, 0, 3, 3, 7])

In [64]:
x.sort() ## x가 가지고 있는 sort메서드를 사용하면 원본이 바뀐 후 저장됨
x

array([0, 3, 3, 5, 7])

In [65]:
idx = np.argsort(x) ## 정렬된 인덱스를 준다 sort랑 다르다 -- sort된 형태의 인덱스를 준다
idx

array([0, 1, 2, 3, 4], dtype=int64)

In [66]:
x[idx]

array([0, 3, 3, 5, 7])